Clarify ingest tool/library names for Ingest CLI and Python Ingest library
Unstructured-IO/docs pull request #131
Opened 2024-07-29 20:51 UTC by Paul-Cornell

There has been a conflation and confusion of "CLI," "Python SDK," and "Python Ingest" for tool/library names throughout the docs. Customers seem to be confused--and the docs seem to reinforce this confusion--with terms such as:

- "CLI" - The CLI can only handle ingest operations in Unstructured. So, preface it with "Ingest" to make that clearer.
- "Python SDK" - The Python SDK cannot actually do multi-file ingestion operations by itself. So, distinguish the SDK from the "Ingest Python library.
- "Open source" - The open source library cannot actually do multi-file ingestion operations by itself. So, distinguish the "open source" library from the "Ingest Python" library.

2024-07-29 21:17 UTC, scanny requested changes
We're going to need a different name instead of "Unstructured Ingest Python". Happy to noodle that with you if no clear alternative presents itself.

2024-07-29 21:17 UTC, scanny commented on api-reference/ingest/destination-connector/astra.mdx
> +Now call the Unstructured Ingest CLI or Unstructured Ingest Python. The source connector can be any of the ones supported. This example uses the local source connector:
`Unstructured Ingest Python` seems an odd name. What would that mean?

I could possibly see `Unstructured Ingest Python API`. Is that what we're talking about?

2024-07-29 21:17 UTC, scanny commented on faq/faq.mdx
> +using the Unstructured REST API POST with `curl`, or the [Unstructured Ingest CLI](/ingestion/overview#unstructured-ingest-cli), or the [Unstructured Python SDK](https://github.com/Unstructured-IO/un
"Unstructured REST API POST" seems an odd name, not sure what that would refer to. I'd be inclined to just say "Unstructured REST API". I don't think the detail that a `curl` request to the API uses the `POST` HTTP method is necessary here. Better to link to an example that includes that detail.

Btw, "boilerplate codes" just above strikes me as misspoken; "boilerplate code" would get it done I expect.

2024-07-30 20:03 UTC, Paul-Cornell commented on api-reference/ingest/destination-connector/astra.mdx
> +Now call the Unstructured Ingest CLI or Unstructured Ingest Python. The source connector can be any of the ones supported. This example uses the local source connector:
There is an open discussion about whether to call it the "Unstructured Ingest Python SDK" or the "Unstructured Ingest Python API." So as to not hold up this PR, I am using the more general term "Unstructured Ingest Python library" in this PR for now. I can certainly create a follow-on PR to replace "library" with "SDK" or "API" once a consensus decision is reached here.

2024-07-30 20:06 UTC, Paul-Cornell commented on faq/faq.mdx
> +using the Unstructured REST API POST with `curl`, or the [Unstructured Ingest CLI](/ingestion/overview#unstructured-ingest-cli), or the [Unstructured Python SDK](https://github.com/Unstructured-IO/un
Sounds good: removed `POST` and `curl`; replaced "boilerplate" with "example."

2024-07-31 11:58 UTC, MKhalusova approved these changes
I think this is a reasonable naming choice.

2024-07-31 14:51 UTC, merged