Add missing ingest connector configuration paramter descriptions
Unstructured-IO/docs pull request #133
Opened 2024-07-29 23:10 UTC by Paul-Cornell

See:

2024-07-30 19:14 UTC, MKhalusova requested changes
Thanks for organizing these! I left a few comments, questions and nitpicks.

2024-07-30 19:14 UTC, MKhalusova commented on snippets/ingest-configuration-shared/chunking-configuration.mdx
> +*   <Icon icon="v"/><Icon icon="2"/>&nbsp;&nbsp;`chunk_combine_text_under_n_chars`: Combine consecutive chunks when the first does not exceed length `n` and the second will fit without exceeding the
I thought this would also work with `by_page` and `by_similarity` strategies. Does it not work with them?

2024-07-30 19:14 UTC, MKhalusova commented on snippets/ingest-configuration-shared/chunking-configuration.mdx
> +*   <Icon icon="v"/><Icon icon="2"/>&nbsp;&nbsp;`chunk_multipage_selections`: `True` to ignore page boundaries when chunking such that elements from two different pages can appear in the same chunk.
Same as earlier, can we confirm that this doesn't work with other strategies? IMO, this should also work with `by_similarity` (but not with `by_page`)

2024-07-30 21:29 UTC, Paul-Cornell commented on snippets/ingest-configuration-shared/partition-configuration.mdx
Good point. Removed. (We cover this in the OSS OCR how-to page anyway.)

2024-07-30 21:30 UTC, Paul-Cornell commented on snippets/ingest-configuration-shared/overview.mdx
> +- [v2 non-fsspec connectors](https://github.com/Unstructured-IO/unstructured/tree/main/unstructured/ingest/v2/processes/connectors)
There's unfortunately no "documentation" for this, outside of the connector implementers' source code. I changed this to "source code" for clarity.

2024-07-30 21:30 UTC, Paul-Cornell commented on snippets/ingest-configuration-shared/overview.mdx
> +Configurations are available for v2 and v1 versions of source connctors, where available.
Fixed typo and re-phrased.

2024-07-30 21:30 UTC, Paul-Cornell commented on snippets/ingest-configuration-shared/overview.mdx
> +*   Congigurations that apply to both v2 and v1 are prefaced by <Icon icon="v"/><Icon icon="2"/>, <Icon icon="v"/><Icon icon="1"/>.
Thanks for the catch!

2024-07-30 21:31 UTC, Paul-Cornell commented on snippets/ingest-configuration-shared/overview.mdx
> +If you're looking for parameters specific to a source connector type (such as authentication options)&mdash;or to determine whether a source connector supports v2 configurations, v1 configurations, o
Good point. Removed.

2024-08-01 16:45 UTC, Paul-Cornell commented on snippets/ingest-configuration-shared/processor-configuration.mdx
> +*   <Icon icon="v"/><Icon icon="2"/>&nbsp;&nbsp;`re_download`: `False` (the default) to not re-download files if they are already present in the download directory.
Asking around internally about this. Will address in a follow-on PR after I get a response.

2024-08-01 16:46 UTC, Paul-Cornell commented on snippets/ingest-configuration-shared/partition-configuration.mdx
> +*   <Icon icon="v"/><Icon icon="2"/>&nbsp;,<Icon icon="v"/><Icon icon="1"/>&nbsp;&nbsp;`additional_partition_args`: A JSON string representation of any values to pass through to the `partition` funct
Asking around internally about this. Will address in a follow-on PR after I get a response.

2024-08-01 16:47 UTC, Paul-Cornell commented on snippets/ingest-configuration-shared/chunking-configuration.mdx
> +*   <Icon icon="v"/><Icon icon="2"/>&nbsp;&nbsp;`chunk_combine_text_under_n_chars`: Combine consecutive chunks when the first does not exceed length `n` and the second will fit without exceeding the
I asked around internally about this and was told no, only for `by_title`. This option is a partial remedy to over-detection of titles which otherwise can produce many chunks that are too small. Would it be worth stating some version of this in the docs though?

2024-08-01 16:49 UTC, Paul-Cornell commented on snippets/ingest-configuration-shared/chunking-configuration.mdx
> +*   <Icon icon="v"/><Icon icon="2"/>&nbsp;&nbsp;`chunk_multipage_selections`: `True` to ignore page boundaries when chunking such that elements from two different pages can appear in the same chunk.
I asked around internally about this and was told no, only for `by_title`. "By-title" is really "by-(document)-section", a document section being a heading (section heading) followed by paragraphs up to the next section heading. By-title promises to keep sections separate, like text from two different sections never appears in the same chunk. When `chunk_multipage_sections` is `False` it also breaks chunks on pages, so like combining `by_title` and `by_page`. Would it be worth stating some version of this in the docs?

2024-08-01 16:50 UTC, Paul-Cornell commented on snippets/ingest-configuration-shared/processor-configuration.mdx
> +*   <Icon icon="v"/><Icon icon="2"/>&nbsp;&nbsp;`max_docs`: The maximum number of documents to process.
Asking around internally about this. Will address in a follow-on PR after I get a response.

2024-08-02 11:58 UTC, MKhalusova approved these changes
LGTM, thank you!

2024-08-02 15:41 UTC, merged