Add split_pdf_* parameters to all related code examples
Unstructured-IO/docs pull request #166
Opened 2024-08-13 23:07 UTC by Paul-Cornell

2024-08-13 23:16 UTC, ninalopatina requested changes
just one note on the default hi_res model in the first file change

2024-08-13 23:16 UTC, ninalopatina commented on api-reference/api-services/examples.mdx
> +  -F 'hi_res_model_name=yolox' \
do we want to update this to layout_v1.1.0 since this is now the preferred model to use?

2024-08-14 11:27 UTC, MKhalusova commented on api-reference/api-services/examples.mdx
> +  -F 'hi_res_model_name=yolox' \
`layout_v1.1.0`. We can show one or the other throughout the documentation, but this comment is unrelated to this PR, we can discuss and address it separately.

2024-08-14 11:27 UTC, MKhalusova approved these changes

2024-08-14 11:28 UTC, MKhalusova commented on api-reference/api-services/examples.mdx
> +  -F 'hi_res_model_name=yolox' \
Please unblock the merge.

2024-08-14 14:15 UTC, Paul-Cornell commented on api-reference/api-services/examples.mdx
> +  -F 'hi_res_model_name=yolox' \
Changed/updated.

2024-08-14 14:16 UTC, merged