Shared concepts
Unstructured-IO/docs pull request #24
Opened 2024-05-01 17:14 UTC by MKhalusova

This PR creates a TOC section called Concepts in both Open Source and API docs. 
This section contains shared markdown snippets describing concepts that relate to both products and which were previously only available in the open source library docs:
- document elements and metadata (used to be split between introduction and a separate section, merged into one documents as it seems logically better, improved the text)
- partitioning strategies (used to be in "best practices" )
- glossary (ex "key concepts")

The PR also improves the structure of the introduction section of the OS library docs and places installation instructions under "Getting Started"

2024-05-01 17:32 UTC, MthwRobinson requested changes
Looks good! Have a few suggestions and linked a recent change to the element IDs.

2024-05-01 17:32 UTC, MthwRobinson commented on open-source/concepts/document-elements.mdx
> +### Extracting additional metadata with regex
I don't believe this feature is widely used and isn't available in the API. I'd lean toward not emphasizing it and potentially deprecating it.

2024-05-01 17:32 UTC, MthwRobinson commented on snippets/concepts/document-elements.mdx
> +Instead of treating all documents like a wall of plain text, Unstructured preserves the semantic structure of the documents.
Another benefit of normalizing to our element type scheme is that you can treat all documents the same in your downstream processing, regardless of source format.

2024-05-01 17:32 UTC, MthwRobinson commented on snippets/concepts/document-elements.mdx
> +By default, an element ID is a SHA-256 hash of the element text. This is to ensure that the ID is deterministic.
That was updated in this PR, and now the hash also includes the page number and the sequence order on the page to make the IDs deterministic and unique.

See [this PR](https://github.com/Unstructured-IO/unstructured/pull/2673).

2024-05-01 17:32 UTC, MthwRobinson commented on snippets/concepts/partitioning-strategies.mdx
> +*   `hi_res`: The "hi_res" strategy identifies the layout of the document using `detectron2`. The advantage of "hi_res" is that it uses the document layout to gain additional information about docume
I've generally been describing hi res vs. fast as "model based workload" vs "rules based workloads", though there's a bit of nuance there since "fast" does incorporate NLP model. But I think that framing is generally accurate and makes things clear.

2024-05-01 17:38 UTC, MKhalusova commented on open-source/concepts/document-elements.mdx
> +### Extracting additional metadata with regex
Gotcha! We can remove it then :)

2024-05-01 17:42 UTC, MKhalusova commented on snippets/concepts/document-elements.mdx
> +By default, an element ID is a SHA-256 hash of the element text. This is to ensure that the ID is deterministic.
That's cool! Didn't know that.

2024-05-01 17:46 UTC, MKhalusova commented on snippets/concepts/document-elements.mdx
> +By default, an element ID is a SHA-256 hash of the element text. This is to ensure that the ID is deterministic.
Is the `unique_element_ids` parameter going to be deprecated then?

2024-05-01 17:52 UTC, MthwRobinson commented on snippets/concepts/document-elements.mdx
> +By default, an element ID is a SHA-256 hash of the element text. This is to ensure that the ID is deterministic.
That's still around and will give you _globally_ unique IDs vs IDs that are guaranteed to be unique within a document. With the deterministic hashing scheme, you could still have clashing IDs if say `"My cool title"` is the first element of the first page for two different docs.

```
By default, the element ID is a SHA-256 hash of the element's text, its position on the page, page number it's on, and the name of the document file - this is to ensure that the ID is deterministic and unique at the document level.
To obtain globally unique IDs in the output (UUIDs), you can pass
``unique_element_ids=True`` into any of the partition functions. This can be helpful
if you'd like to use the IDs as a primary key in a database, for example.
```

2024-05-01 17:53 UTC, MthwRobinson commented on snippets/concepts/document-elements.mdx
> +By default, an element ID is a SHA-256 hash of the element text. This is to ensure that the ID is deterministic.
@micmarty-deepsense - Does that sounds right based on the logic from your PR?

2024-05-01 17:57 UTC, MthwRobinson approved these changes
LGTM! Verified all my comments were resolved

2024-05-01 17:58 UTC, merged

2024-05-10 13:17 UTC, micmarty-deepsense commented on snippets/concepts/document-elements.mdx
> +By default, an element ID is a SHA-256 hash of the element text. This is to ensure that the ID is deterministic.
sorry for late response, didn't see your message :(


> That's still around and will give you _globally_ unique IDs vs IDs that are guaranteed to be unique within a document. With the deterministic hashing scheme, you could still have clashing IDs if say `"My cool title"` is the first element of the first page for two different docs.
> 
> ```
> By default, the element ID is a SHA-256 hash of the element's text, its position on the page, page number it's on, and the name of the document file - this is to ensure that the ID is deterministic and unique at the document level.
> To obtain globally unique IDs in the output (UUIDs), you can pass
> ``unique_element_ids=True`` into any of the partition functions. This can be helpful
> if you'd like to use the IDs as a primary key in a database, for example.
> ```

Yes, that sounds right 😌