Airtable v2 source connector
Unstructured-IO/docs pull request #248
Opened 2024-09-21 00:12 UTC by Paul-Cornell

Work in progress.

2024-09-25 12:45 UTC, MKhalusova requested changes
A couple of small changes needed, please see the comments.

2024-09-25 12:45 UTC, MKhalusova commented on api-reference/ingest/source-connectors/airtable.mdx
> +Now call the Unstructured CLI or Python SDK. The source connector can be any of the ones supported. This example uses the local source connector:
You mean the destination can be any of the ones supported? 
We're using Airtable here as a source.

2024-09-25 12:45 UTC, MKhalusova commented on open-source/ingest/source-connectors/airtable.mdx
> +Now call the Unstructured CLI or Python. The source connector can be any of the ones supported. This example uses the local source connector.
Same here, the destination can be any of the ones supported. We're using Airtable as a source.

2024-09-25 12:45 UTC, MKhalusova commented on snippets/general-shared-text/airtable.mdx
> +The Airtable connector prerequisites:
This text doesn't show up on the staged pages for some reason.

2024-09-25 15:04 UTC, Paul-Cornell commented on api-reference/ingest/source-connectors/airtable.mdx
> +Now call the Unstructured CLI or Python SDK. The source connector can be any of the ones supported. This example uses the local source connector:
Good catch! A copy-paste error. In fact, I went through and noticed this error in several other files. Fixing those now as well.

2024-09-25 15:06 UTC, Paul-Cornell commented on snippets/general-shared-text/airtable.mdx
> +The Airtable connector prerequisites:
Looks like a Mintlify GitHub build timing issue. I can see it fine in my local build.

2024-09-26 17:18 UTC, MKhalusova approved these changes

2024-09-26 18:12 UTC, merged