Outlook v2 source connector
Unstructured-IO/docs pull request #286
Opened 2024-10-17 21:42 UTC by Paul-Cornell

See

2024-10-17 23:51 UTC, Paul-Cornell commented on snippets/general-shared-text/outlook.mdx
> +- The Outlook user's email address.
```suggestion
The Outlook prerequisites:

<iframe
width="560"
height="315"
src="https://www.youtube.com/embed/9yESRp9pzv0"
title="YouTube video player"
frameborder="0"
allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
allowfullscreen
></iframe>

- The Outlook user's email address.
```

2024-10-21 21:21 UTC, ninalopatina requested changes

2024-10-21 21:21 UTC, ninalopatina commented on snippets/source_connectors/outlook.v2.py.mdx
> +        embedder_config=EmbedderConfig(embedding_provider="huggingface"),
is there a reason these are all missing the chunking step before the embedding step?

2024-10-21 22:09 UTC, Paul-Cornell commented on snippets/source_connectors/outlook.v2.py.mdx
> +        embedder_config=EmbedderConfig(embedding_provider="huggingface"),
Hmm...not sure. I'll add them now though!

2024-10-21 22:10 UTC, Paul-Cornell commented on snippets/source_connectors/outlook.v2.py.mdx
> +        embedder_config=EmbedderConfig(embedding_provider="huggingface"),
What kind of chunking strategy here--is "by_title" reasonable?

2024-10-22 15:11 UTC, Paul-Cornell commented on snippets/source_connectors/outlook.v2.py.mdx
> +        embedder_config=EmbedderConfig(embedding_provider="huggingface"),
Added "by_title".

2024-10-22 23:09 UTC, ninalopatina approved these changes

2024-10-22 23:20 UTC, merged