Update api-parameters.mdx
Unstructured-IO/docs pull request #61
Opened 2024-06-03 19:59 UTC by CodesLikeIcarus

I think to minimize friction, we need to provide the models and a description of why to use certain models over others. Need to validate the following list with ENG and then provide a short write-up table of each : `yolox`, `yolox_quantized`, `yolox_tiny`,`layout_v1.1.0`, `detectron2_onnx`, `detectron2_quantized`, `detectron2_mask_rcnn`, `chipperv1`, `chipperv2`,`chipperv3`

2024-06-03 20:36 UTC, cragwolfe requested changes
we shouldn't publicly mention `layout_v1.1.0` until it is the default model

2024-06-24 21:58 UTC, awalker4 approved these changes
The list LGTM, I verified that all these model names work in serverless except Chipper.

Notes:
* Chipper isn't available anywhere at the moment, let's remove for now
* The default is now `layout_v1.1.0`
* We should definitely get a models page going for the api. We have the [open source doc](https://docs.unstructured.io/open-source/concepts/models). Perhaps we need a shared page of all the models with asterisk next to the paid ones. Then the api and open source can both refer back.

2024-07-02 15:14 UTC, Paul-Cornell commented
Thanks @CodesLikeIcarus and @awalker4 for the proposal to create a models page. Let me create an internal tracking item for this.

2024-07-08 15:27 UTC, cragwolfe approved these changes

2024-07-08 15:56 UTC, merged